### ISSUE TITLE
grpc greeter example can not run

### ISSUE THREAD

**Issue by hopehook** [micro/examples#23]
code url: https://github.com/micro/examples/tree/master/grpc/greeter

error info:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x133d5a2]

goroutine 1 [running]:
github.com/micro/go-micro/metadata.FromContext(0x0, 0x0, 0xc420158c60, 0x0)
	/Users/tanshuai/lab/go/src/github.com/micro/go-micro/metadata/metadata.go:16 +0x22
github.com/micro/go-micro.(*clientWrapper).setHeaders(0xc420150680, 0x0, 0x0, 0x1698b8a, 0x9)
	/Users/tanshuai/lab/go/src/github.com/micro/go-micro/wrapper.go:18 +0x85
github.com/micro/go-micro.(*clientWrapper).Call(0xc420150680, 0x0, 0x0, 0x19a82a0, 0xc420068540, 0x160e020, 0xc42003da30, 0x0, 0x0, 0x0, ...)
	/Users/tanshuai/lab/go/src/github.com/micro/go-micro/wrapper.go:35 +0x46
github.com/micro/examples/grpc/greeter/srv/proto/hello.(*sayService).Hello(0xc420150ba0, 0x0, 0x0, 0xc42003da20, 0x0, 0x0, 0x0, 0xc42004bf70, 0x1006184, 0xc420072058)
	/Users/tanshuai/lab/go/src/github.com/micro/examples/grpc/greeter/srv/proto/hello/hello.micro.go:69 +0x145
main.main()
	/Users/tanshuai/lab/go/src/github.com/micro/examples/grpc/greeter/cli/main.go:26 +0x157
exit status 2
```

**Comment by asim** [comment]
Are you modifying the code in some way? This works perfectly fine for me.

**Comment by hopehook** [comment]
@asim No.  When I copy code snippet from here to write my own grpc example,  this error occured. I have not find any problem in my code, util I run this example directly,  the same error occured. So, perhaps my environment has some problem ? This bothers me for a long time, I will try it on other OS system later.

**Comment by asim** [comment]
What it's implying is the context or the metadata its looking at is nil. This code runs absolutely fine unmodified so it can only imply that there has been a modification on your end to cause it to fail.

**Comment by hopehook** [comment]
@asim Awesome, the parameter ctx is nil. 😆

**Comment by hopehook** [comment]
Another one problem,  help me please!
When my demo use GRPC, it will raise error: context deadline exceeded.
When my demo use MICRO, it successfully return data.

1. Differences:
 * server
```
service := grpc.NewService(
	micro.Name(MicroName),
	micro.RegisterTTL(time.Second*30),
	micro.RegisterInterval(time.Second*10),
)
```
```
service := micro.NewService(
	micro.Name(MicroName),
	micro.RegisterTTL(time.Second*30),
	micro.RegisterInterval(time.Second*10),
)
```

 * client
```
service := grpc.NewService()
service.Init()

// use the generated client stub
OrderServiceClient = proto.NewOrderServiceClient("go.micro.srv.order", service.Client())
```
```
service := micro.NewService()
service.Init()

// use the generated client stub
OrderServiceClient = proto.NewOrderServiceClient("go.micro.srv.order", service.Client())
```

2. My proto file: order.proto
```
syntax = "proto3";
service OrderService {
	rpc GetOrders(GetOrdersRequest) returns (GetOrdersResponse) {}
}
message GetOrdersRequest {
    int32 page_index = 1;
    int32 page_count = 2;
}
message GetOrdersResponse {
	repeated Order orders = 1;
}
message Order {
    uint64 id = 1;
    string code = 2;
    uint64 user_id = 3;
    string title = 4;
    int64 price = 5;
    string create_time = 6;
    string update_time = 7;
}
```

3. My request code:
```
func GetOrderList(w http.ResponseWriter, r *http.Request) {
	// Set arbitrary headers in context
	ctx := metadata.NewContext(context.Background(), map[string]string{
		"X-User-Id": "john",
		"X-From-Id": "script",
	})
	rsp, err := g.OrderServiceClient.GetOrders(ctx, &proto.GetOrdersRequest{
		PageIndex: 0,
		PageCount: 10,
	})
	if err != nil {
		CommonWrite(w, r, -1, err.Error(), nil)
		return
	}
	CommonWriteSuccess(w, r, rsp.Orders)
}

```

4. My response code:
```
type OrderHandler struct{}

func (*OrderHandler) GetOrders(ctx context.Context, req *proto.GetOrdersRequest, rsp *proto.GetOrdersResponse) error {
	orders, err := model.GetOrders(req.PageIndex, req.PageCount)
	if err != nil {
		return err
	}
	rsp.Orders = orders
	return nil
}
```
